version: '3'
services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
  nginx:
    image: nginx 
    container_name: nginx
    ports:
      - 80:80 
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: samurai
      MYSQL_PASSWORD: nobunaga
    ports:
      - 3306:3306
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
